In [4]:
## Import required dependencies

import os
import psycopg2
import pandas as pd 
from PIL import Image
import streamlit as st
import plotly.express as px
from dotenv import load_dotenv
from sqlalchemy import create_engine, Integer, String


# load environment variables

load_dotenv()

API_KEY         =   os.getenv("API_KEY")
API_HOST        =   os.getenv("API_HOST")
DB_NAME         =   os.getenv("DB_NAME")
DB_USER         =   os.getenv("DB_USER")
DB_PASS         =   os.getenv("DB_PASS")
DB_HOST         =   os.getenv("DB_HOST")
DB_PORT         =   int(os.getenv("DB_PORT"))


# Create the database connection string
connection_string = f'postgresql+psycopg2://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}'

# Create the sqlalchemy engine
engine = create_engine(connection_string)

# Query to view the newly created table
query = f'SELECT * FROM public.performance_metrics_vw'
# Execute the query and store the result in a DataFrame for easy viewing
premier_league_standings = pd.read_sql(query, engine)
premier_league_standings

    position               team  games_played  wins  draws  losses
0          1    Manchester City            38    27      5       6
1          2  Manchester United            38    21     11       6
2          3          Liverpool            38    20      9       9
3          4          Leicester            38    20      6      12
4          5            Chelsea            38    19     10       9
5          6           West Ham            38    19      8      11
6          7          Tottenham            38    18      8      12
7          8            Arsenal            38    18      7      13
8          9              Leeds            38    18      5      15
9         10            Everton            38    17      8      13
10        11        Aston Villa            38    16      7      15
11        12             Wolves            38    12      9      17
12        12          Newcastle            38    12      9      17
13        14     Crystal Palace            38    12      8      18
14        15        Southampton            38    12      7      19
15        16            Burnley            38    10      9      19
16        17           Brighton            38     9     14      15
17        18      Sheffield Utd            38     7      2      29
18        19             Fulham            38     5     13      20
19        20          West Brom            38     5     11      22

In [5]:
DB_PORT

5432

In [6]:
# Set the page configuration of the app
st.set_page_config(
    page_title   =  "Premier League Standings 2023/24",
    page_icon    =  "âš½",
    layout       =  "wide"
)